### ISSUE TITLE
systemd start

### ISSUE THREAD

**Issue by juanjoSanz** [mpeirone/QnapLcdInfo#1]
I create a systemd service to start this script automatically

Just copy code below into `/etc/systemd/system/qnaplcdinfo.service`

```
[Unit]
Description=Qnap LCD Info Service
After=syslog.target

[Service]
Type=simple
Restart=on-failure
ExecStart=/srv/QnapLcdInfo/lcdInfo.py

[Install]
WantedBy=multi-user.target
```

Then enable and start service

```
systemctl enable qnaplcdinfo.service
systemctl start qnaplcdinfo.service
```

**Comment by mpeirone** [comment]
Awesome!!! I just see it now, sorry. In the next few weeks I plan to refactor the repository, I will include it!
Thank you very much!
